### ISSUE TITLE
SaveActions error using last release 0.0.23

### ISSUE THREAD

**Issue by daniel-grana** [spring-io/spring-javaformat#207]
I have updated the plugin to the last version (0.0.23) in my Eclipse 2020-03 and, when I save any java file, it is produced the following error:

![image](https://user-images.githubusercontent.com/21100553/87633201-3a19f900-c73b-11ea-99d0-abbe06fdbed9.png)

Inspecting the error log, you can see:

```
!ENTRY org.eclipse.jdt.ui 4 10006 2020-07-16 07:58:58.337
!MESSAGE The save participant 'org.eclipse.jdt.ui.postsavelistener.cleanup' caused an exception: java.lang.IllegalArgumentException
!STACK 0
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:241)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:134)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.createParser(DefaultCodeFormatter.java:337)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.parseSourceCode(DefaultCodeFormatter.java:318)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:222)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.format(DefaultCodeFormatter.java:186)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.format(DefaultCodeFormatter.java:168)
	at io.spring.javaformat.formatter.Formatter.lambda$format$0(Formatter.java:102)
	at io.spring.javaformat.formatter.Formatter.nlsSafe(Formatter.java:149)
	at io.spring.javaformat.formatter.Formatter.format(Formatter.java:101)
	at io.spring.javaformat.eclipse.formatter.SpringCodeFormatter.format(SpringCodeFormatter.java:39)
	at org.eclipse.jdt.internal.corext.util.CodeFormatterUtil.reformat(CodeFormatterUtil.java:291)
	at org.eclipse.jdt.internal.corext.util.CodeFormatterUtil.reformat(CodeFormatterUtil.java:354)
	at org.eclipse.jdt.internal.corext.fix.CodeFormatFix.createCleanUp(CodeFormatFix.java:74)
	at org.eclipse.jdt.internal.ui.fix.CodeFormatCleanUp.createFix(CodeFormatCleanUp.java:64)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.calculateChange(CleanUpRefactoring.java:779)
	at org.eclipse.jdt.internal.corext.fix.CleanUpPostSaveListener.saved(CleanUpPostSaveListener.java:388)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider$5.run(CompilationUnitDocumentProvider.java:1650)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
```

I attach complete error log
[java-format-error.log](https://github.com/spring-io/spring-javaformat/files/4929616/java-format-error.log)

If I configure project settings and change the formatter implementation ( _Properties > Java Code Style > Formatter_) and select _Eclipse [built-in]_ it works well and any error is produced.

Regards.

**Comment by wilkinsona** [comment]
Unfortunately, there are quite frequent breaking changes in Eclipse JDT that mean that this plugin is somewhat coupled to a particular version of JDT. You'll need to either use 2020-03 with the Java 14 support installed or 2020-06.

I'll leave this open for now to see if we can restore compatibility with 2020-03 but that may not be possible. If you need to use Eclipse 2020-03, you'll have to stick with 0.0.22 for now at least.

**Comment by daniel-grana** [comment]
Thank you so much! I'll rollback to 0.0.22 for now. Expecting that next release will be compatible with Eclipse 2020-03.

**Comment by wilkinsona** [comment]
Please don't expect that it will be compatible. As I said above, we'll see what we can do but it may not be possible or may not be worth the complexity that it would introduce.

**Comment by philwebb** [comment]
Unfortunately we're unable to find an easy way to support old versions.
