### ISSUE TITLE
UnsupportedOperation exception thrown with IntelliJ 2020.2

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-javaformat#213]
This exception is thrown when our formatter is active: https://github.com/JetBrains/intellij-community/blob/9bbaa4b940f823b33359911df9f5f9363c549064/platform/core-api/src/com/intellij/psi/codeStyle/CodeStyleManager.java#L351

**Comment by philwebb** [comment]
Working past that gives:

```
Plugin 'spring-javaformat' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: org/eclipse/jface/text/IDocument
    at io.spring.format.formatter.intellij.codestyle.SpringCodeStyleManager.<init>(SpringCodeStyleManager.java:39)
    at io.spring.format.formatter.intellij.SpringFormatComponent.update(SpringFormatComponent.java:100)
    at io.spring.format.formatter.intellij.SpringFormatComponent.initComponent(SpringFormatComponent.java:76)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:258)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:110)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:177)
    at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:221)
    at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:47)
    at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(ProjectManagerExImpl.kt:102)
    at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(ProjectManagerExImpl.kt:47)
    at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$1$progressTask$1.run(ProjectFrameAllocator.kt:84)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jface.text.IDocument PluginClassLoader[PluginDescriptor(name=spring-javaformat, id=spring-javaformat, path=/Users/pwebb/Library/Application Support/JetBrains/IdeaIC2020.2/plugins/original-spring-javaformat-intellij-plugin-0.0.25-SNAPSHOT.jar, version=1.0)] com.intellij.ide.plugins.cl.PluginClassLoader@33bd027b
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 33 more
```
