### ISSUE TITLE
AssertionError: Wrong line separators: '\r\n' on Windows

### ISSUE THREAD

**Issue by alexanderabramov** [spring-io/spring-javaformat#65]
With plugin v0.0.6, on Windows 10, Intellij IDEA 2018.2, trying to reformat results in the following IDE error.

Expected behavior - the plugin should not complain about line separators standard for Windows. They will be converted by git when committing.

```
ReformatCodeProcessor failure, see the stack trace

java.lang.AssertionError: Wrong line separators: '\r\n' at offset 0
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2688)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:675)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:597)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:590)
	at io.spring.format.formatter.intellij.codestyle.EclipseDocumentAdapter.replace(EclipseDocumentAdapter.java:41)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1120)
	at org.eclipse.text.edits.ReplaceEdit.performDocumentUpdating(ReplaceEdit.java:85)
	at org.eclipse.text.edits.TextEdit.traverseDocumentUpdating(TextEdit.java:913)
	at org.eclipse.text.edits.TextEdit.traverseDocumentUpdating(TextEdit.java:906)
	at org.eclipse.text.edits.TextEditProcessor.executeDo(TextEditProcessor.java:193)
	at org.eclipse.text.edits.TextEdit.dispatchPerformEdits(TextEdit.java:735)
	at org.eclipse.text.edits.TextEditProcessor.performEdits(TextEditProcessor.java:155)
	at org.eclipse.text.edits.TextEdit.apply(TextEdit.java:707)
	at org.eclipse.text.edits.TextEdit.apply(TextEdit.java:731)
	at io.spring.format.formatter.intellij.codestyle.SpringReformatter.lambda$applyEdit$2(SpringReformatter.java:113)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:364)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:124)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:265)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:264)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:322)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:131)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:107)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:324)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:126)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:364)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:356)
	at io.spring.format.formatter.intellij.codestyle.SpringReformatter.runWriteCommandAction(SpringReformatter.java:123)
	at io.spring.format.formatter.intellij.codestyle.SpringReformatter.applyEdit(SpringReformatter.java:110)
	at io.spring.format.formatter.intellij.codestyle.SpringReformatter.reformat(SpringReformatter.java:105)
	at io.spring.format.formatter.intellij.codestyle.SpringReformatter.reformat(SpringReformatter.java:77)
	at io.spring.format.formatter.intellij.codestyle.SpringCodeStyleManager.reformat(SpringCodeStyleManager.java:70)
	at io.spring.format.formatter.intellij.codestyle.SpringCodeStyleManager.reformatText(SpringCodeStyleManager.java:58)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$0(ReformatCodeProcessor.java:117)
...
```

**Comment by FalconIA** [comment]
Same issue under windows.

**Comment by findus** [comment]
I'm experiencing the same problem. Still no solution?

IntelliJ IDEA 2018.3.5 (Community Edition)
Build #IC-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
